/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 kitchen.gltf
Author: Fernando Araújo (https://sketchfab.com/nandoshift)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/simple-house-kitchen-b391feaf38be410c9829821ecc93a9bc
Title: Simple House - Kitchen
*/

import React from "react";
import { useGLTF } from "@react-three/drei/core";
import kitchen from "./kitchen.gltf";

export function KitchenModel(props) {
  const { nodes, materials } = useGLTF(kitchen);
  return (
    <group {...props} dispose={null}>
      <group position={[9.78, -0.2, -3.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object718_Object718_mtl_0.geometry}
          material={materials.Object718_mtl}
          position={[-9.78, -3.9, 0.2]}
        />
      </group>
      <group position={[9.78, -0.2, -3.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-9.78, -3.9, 0.2]}>
          <mesh
            geometry={nodes.Object719_Object719_mtl_0.geometry}
            material={materials.Object719_mtl}
          />
          <mesh
            geometry={nodes.Object719_Object719_mtl_0_1.geometry}
            material={materials.Object719_mtl}
          />
          <mesh
            geometry={nodes.Object719_Object719_mtl_0_2.geometry}
            material={materials.Object719_mtl}
          />
          <mesh
            geometry={nodes.Object719_Object719_mtl_0_3.geometry}
            material={materials.Object719_mtl}
          />
        </group>
      </group>
      <group position={[9.78, -0.2, -3.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object720_Object720_mtl_0.geometry}
          material={materials.Object720_mtl}
          position={[-9.78, -3.9, 0.2]}
        />
      </group>
      <group position={[9.78, -0.2, -3.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object721_Object721_mtl_0.geometry}
          material={materials.Object721_mtl}
          position={[-9.78, -3.9, 0.2]}
        />
      </group>
      <group position={[9.78, -0.2, -3.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object722_Object722_mtl_0.geometry}
          material={materials.Object722_mtl}
          position={[-9.78, -3.9, 0.2]}
        />
      </group>
      <group position={[9.78, -0.2, -3.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object723_Object723_mtl_0.geometry}
          material={materials.Object723_mtl}
          position={[-9.78, -3.9, 0.2]}
        />
      </group>
      <group position={[9.78, -0.2, -3.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object724_Object724_mtl_0.geometry}
          material={materials.Object724_mtl}
          position={[-9.78, -3.9, 0.2]}
        />
      </group>
      <group position={[9.78, -0.2, -3.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object725_Object725_mtl_0.geometry}
          material={materials.Object725_mtl}
          position={[-9.78, -3.9, 0.2]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(kitchen);
